apiVersion: v1
kind: Service
metadata:
  name: devops-challenge
  labels:
    app: devops-challenge
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: devops-challenge

